### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by batarian71** [ikatyang/emoji-cheat-sheet#273]
Hello. I am a graphic designer. I want to volunteer support for open source projects. If you want, I can design a logo for you. What do you say? Also tell me if you want something. I can design.

**Comment by ikatyang** [comment]
Hi, thanks for your support, but I think this project is too small that it'll probably waste your logo, there should be a better place for your logo to place. I saw [openlogos](https://github.com/arasatasaygin/openlogos) recently and thought it's a good idea, you could probably create a similar repository for your logos. 😊
