### ISSUE TITLE
Feature request : Generate PDF of README

### ISSUE THREAD

**Issue by darkRaspberry** [ikatyang/emoji-cheat-sheet#484]
may be you can generate a pdf version of the readme. So that anyone can print it and use it quickly.
MAY be. else you are awesome.

**Comment by ikatyang** [comment]
I'm not sure if it's a good idea since PDF is supposed to be portable, i.e., looks the same across all platform, but the emoji actually looks different on different platform, see [Emojipedia](https://emojipedia.org/thinking-face/) for more example.

**Comment by darkRaspberry** [comment]
@ikatyang Yup you are right But I think i can find quick reference after printing this than scrolling or using `ctrl+f`. Anyway its your choice. You may close this.
