### ISSUE TITLE
Superb😀

### ISSUE THREAD

**Issue by Tonystark-300** [ikatyang/emoji-cheat-sheet#495]
Amazing repo...glad to get it.

**Comment by Sukhman723** [comment]
how to use it man

**Comment by Tonystark-300** [comment]
just paste the code as it is in README file. 
like :laughing: and then commit

**Comment by Sukhman723** [comment]
I know you are an expert but i'm not. I'm an artist and if i'll give you
any answer in my artistic language, can you understand?
