### ISSUE TITLE
GitHub icon fails in dark mode

### ISSUE THREAD

**Issue by sergiks** [ikatyang/emoji-cheat-sheet#500]
GitHub icon has the cat as a "hole", should be a shape, filled with light grey. 

In "night" GitHub mode the icon is not visible, renders dark on dark background.

**Comment by sergiks** [comment]
pardon, wrong repo!  Intended for [get-icon/geticon](https://github.com/get-icon/geticon)

**Comment by Igtuhg** [comment]
@thcrack @ikatyang @thcrack
