### ISSUE TITLE
beetle is not working

### ISSUE THREAD

**Issue by marcospds** [ikatyang/emoji-cheat-sheet#532]
The beetle emoji is no longer working?

Here in the text editor it works, but in the preview it doesn't work.

🪲 

Md https://github.com/ikatyang/emoji-cheat-sheet:
![beetle](https://user-images.githubusercontent.com/8590404/133796630-2e615b79-7c1a-4e7b-98a9-7e308a6380b5.png)
Text editor:
![Captura de tela de 2021-09-17 11-15-40](https://user-images.githubusercontent.com/8590404/133797970-8ebff54d-f25a-482e-801e-911193c57ac7.png)
Preview:
![Captura de tela de 2021-09-17 11-16-06](https://user-images.githubusercontent.com/8590404/133797724-f4564780-1c97-44a7-975d-c54743e3d421.png)

**Comment by ikatyang** [comment]
Hi, the `:beetle:` emoji seems working to me. If you still encounter such issue, you may have to contact GitHub support for troubleshooting.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/8341033/137611000-b9be5281-984f-437c-8f15-088b523bd457.png">
