### ISSUE TITLE
Ancêtre commun eucaryote ?

### ISSUE THREAD

**Issue by Gustavebod** [ikatyang/emoji-cheat-sheet#534]
Re-bonjour @AxelCuche,

Je me demandais comment on appelait l'ancêtre commun des organismes eucaryotes 
<html>
<body>

:shipit:
--

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by AxelCuche** [comment]
Re-bonjour @Gustavebod, il s'agit de **L**ast **E**ucaryotic **C**ommon **A**ncestor
