### ISSUE TITLE
Miscategorized flags

### ISSUE THREAD

**Issue by EtchedPixels** [ikatyang/emoji-cheat-sheet#586]
Your cheat sheet is awesome but it's sticking Wales/Scotland/England into a weird category of 'subdivisions', which is not the case. All three should be in the country section just as members of the EU are countries so members of the United Kingdom are themselves countries.

**Comment by ikatyang** [comment]
Hi, we simply use categories from [Unicode Full Emoji List](https://unicode.org/emoji/charts/full-emoji-list.html) to categorize them, you may have to ask them if you have question for the categorization.
