### ISSUE TITLE
[🖇️](https://www.aajtak.in/visualstories/technology/whatsapp-setting-will-use-your-excessive-data-ttec-19836-27-01-2023)

### ISSUE THREAD

**Issue by Nchouhan338** [ikatyang/emoji-cheat-sheet#627]
[🖇️](https://www.aajtak.in/visualstories/technology/whatsapp-setting-will-use-your-excessive-data-ttec-19836-27-01-2023)

_Originally posted by @Nchouhan338 in https://github.com/ikatyang/emoji-cheat-sheet/issues/607#issuecomment-1411438116_

**Comment by Appuappu9207** [comment]
assets/images/electrocat.png
