### ISSUE TITLE
How does Github decide on the :EMOJICODE: name? And what are the current :EMOJICODE: systems (Slack, iOS, Android)? 

### ISSUE THREAD

**Issue by BingeCode** [ikatyang/emoji-cheat-sheet#638]
I know that some service or OS providers have different :EMOJICODE: syntax. Apple uses different key words or search words than Github for example. Other services (like Slack I believe) are based on Githubs syntax. Any good resource where you can find all current one's and compare? I want to build an extension that allows users to use :EMOJICODE: anywhere via a OS configuration.

**Comment by ikatyang** [comment]
I believe https://emojipedia.org should be the one you're looking for, and you may have to contact GitHub for more info about the GitHub stuff.
