### ISSUE TITLE
Request for the addition of "coin" emoji onto the list 🟡

### ISSUE THREAD

**Issue by Imjam88** [ikatyang/emoji-cheat-sheet#667]
Not sure if it was just me or not but when I was scrolling through the list, the emoji :coin: was missing, it looks like this right now. 🪙 I did some research and apparently it's not supported across all platform.

🟡 replacement

**Comment by ikatyang** [comment]
Hi, the emojis you mentioned seem to be already present in the sheet, and the actual rendered image may vary across platforms as far as I can tell. Let me know if I missed something, thank you!

| ico             | shortcode         |
| --------------- | ----------------- |
| :coin:          | `:coin:`          |
| :yellow_circle: | `:yellow_circle:` |
