### ISSUE TITLE
Milestones 

### ISSUE THREAD

**Issue by shaggyd4200063** [ikatyang/emoji-cheat-sheet#675]
I've completed two tours in Iraq and one in Afghanistan.  I received a Purple Heart 💜,  a Distinguished Service Cross, two Silver Stars, and a Bronze Star while serving the 9 years I served in the armed forces.

**Comment by brent85** [comment]
> I've completed two tours in Iraq and one in Afghanistan. I received a Purple Heart 💜, a Distinguished Service Cross, two Silver Stars, and a Bronze Star while serving the 9 years I served in the armed forces.

[](url)
